"""model catalog tables and user role

Revision ID: 977a6b130881
Revises: 957994395e49
Create Date: 2026-09-26 23:07:34.499400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '977a6b130881'
down_revision: Union[str, Sequence[str], None] = '957994395e49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_providers',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalog_models',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('provider_id', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['catalog_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(
        'users',
        sa.Column('role', sa.Text(), server_default='user', nullable=False),
    )

    # ── Seed the catalog with the previously hard-coded registry ──────
    providers_table = sa.table(
        'catalog_providers',
        sa.column('id', sa.Text),
        sa.column('label', sa.Text),
        sa.column('sort_order', sa.Integer),
        sa.column('enabled', sa.Integer),
    )
    models_table = sa.table(
        'catalog_models',
        sa.column('id', sa.Text),
        sa.column('provider_id', sa.Text),
        sa.column('label', sa.Text),
        sa.column('sort_order', sa.Integer),
        sa.column('enabled', sa.Integer),
    )

    seed_providers: list[dict] = []
    seed_models: list[dict] = []
    for p_order, (pid, plabel, models) in enumerate(_SEED_CATALOG):
        seed_providers.append(
            {"id": pid, "label": plabel, "sort_order": p_order, "enabled": 1}
        )
        for m_order, (mid, mlabel) in enumerate(models):
            seed_models.append(
                {
                    "id": mid,
                    "provider_id": pid,
                    "label": mlabel,
                    "sort_order": m_order,
                    "enabled": 1,
                }
            )

    op.bulk_insert(providers_table, seed_providers)
    op.bulk_insert(models_table, seed_models)
    # ### end Alembic commands ###


# (provider id, provider label, [(model id, model label), ...]) — mirrors the
# hard-coded _MODEL_CATALOG that lived in app/api/models.py before this
# migration. The admin console manages this data from now on.
_SEED_CATALOG: list[tuple[str, str, list[tuple[str, str]]]] = [
    ("openai", "OpenAI", [
        ("openai/gpt-4o", "gpt-4o"),
        ("openai/gpt-4o-mini", "gpt-4o-mini"),
        ("openai/gpt-4.1", "gpt-4.1"),
        ("openai/gpt-4.1-mini", "gpt-4.1-mini"),
        ("openai/gpt-4.1-nano", "gpt-4.1-nano"),
        ("openai/o3", "o3"),
        ("openai/o3-mini", "o3-mini"),
        ("openai/o4-mini", "o4-mini"),
    ]),
    ("claude", "Claude (Anthropic)", [
        ("anthropic/claude-sonnet-4-20250514", "claude-sonnet-4"),
        ("anthropic/claude-3-5-sonnet-20241022", "claude-3.5-sonnet"),
        ("anthropic/claude-3-5-haiku-20241022", "claude-3.5-haiku"),
        ("anthropic/claude-3-haiku-20240307", "claude-3-haiku"),
    ]),
    ("gemini", "Gemini (Google)", [
        ("gemini/gemini-2.5-pro", "Gemini 2.5 Pro"),
        ("gemini/gemini-2.5-flash", "Gemini 2.5 Flash"),
        ("gemini/gemini-2.0-flash", "Gemini 2.0 Flash"),
        ("gemini/gemini-1.5-pro", "Gemini 1.5 Pro"),
        ("gemini/gemini-1.5-flash", "Gemini 1.5 Flash"),
    ]),
    ("qwen", "Qwen (Alibaba)", [
        ("qwen/qwen-plus", "Qwen Plus"),
        ("qwen/qwen-turbo", "Qwen Turbo"),
        ("qwen/qwen-max", "Qwen Max"),
        ("qwen/qwen2.5-72b-instruct", "Qwen 2.5 72B Instruct"),
        ("qwen/qwen2.5-32b-instruct", "Qwen 2.5 32B Instruct"),
    ]),
    ("huggingface", "🤗 Open Models (Free via HuggingFace)", [
        ("huggingface/meta-llama/Llama-3.1-8B-Instruct", "Llama 3.1 8B Instruct (Free)"),
        ("huggingface/meta-llama/Llama-3.2-3B-Instruct", "Llama 3.2 3B Instruct (Free)"),
        ("huggingface/mistralai/Mistral-7B-Instruct-v0.3", "Mistral 7B Instruct (Free)"),
        ("huggingface/mistralai/Mixtral-8x7B-Instruct-v0.1", "Mixtral 8x7B MoE (Free)"),
        ("huggingface/Qwen/Qwen2.5-7B-Instruct", "Qwen 2.5 7B Instruct (Free)"),
        ("huggingface/Qwen/Qwen2.5-Coder-7B-Instruct", "Qwen 2.5 Coder 7B (Free)"),
        ("huggingface/deepseek-ai/DeepSeek-R1-Distill-Qwen-7B", "DeepSeek R1 Distill 7B (Free)"),
    ]),
    ("llama", "Llama (via HuggingFace)", [
        ("llama/meta-llama/Llama-3.1-8B-Instruct", "Llama 3.1 8B Instruct"),
        ("llama/meta-llama/Llama-3.2-3B-Instruct", "Llama 3.2 3B Instruct"),
    ]),
    ("mistral", "Mistral (via HuggingFace)", [
        ("mistral/mistralai/Mistral-7B-Instruct-v0.3", "Mistral 7B Instruct"),
        ("mistral/mistralai/Mixtral-8x7B-Instruct-v0.1", "Mixtral 8x7B Instruct"),
    ]),
    ("deepseek", "DeepSeek", [
        ("deepseek/deepseek-ai/DeepSeek-R1-Distill-Qwen-7B", "DeepSeek R1 Distill Qwen 7B"),
    ]),
]


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_table('catalog_models')
    op.drop_table('catalog_providers')
    # ### end Alembic commands ###
